/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValidadesRouteImport } from './routes/_authenticated/validades'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedProcessosModelosRouteImport } from './routes/_authenticated/processos-modelos'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated/processos'
import { Route as AuthenticatedPortalProcessosRouteImport } from './routes/_authenticated/portal-processos'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedMinhasPendenciasRouteImport } from './routes/_authenticated/minhas-pendencias'
import { Route as AuthenticatedMinhaAreaRouteImport } from './routes/_authenticated/minha-area'
import { Route as AuthenticatedMeusProcessosRouteImport } from './routes/_authenticated/meus-processos'
import { Route as AuthenticatedMeusDocumentosRouteImport } from './routes/_authenticated/meus-documentos'
import { Route as AuthenticatedMeuMesRouteImport } from './routes/_authenticated/meu-mes'
import { Route as AuthenticatedInteracoesRouteImport } from './routes/_authenticated/interacoes'
import { Route as AuthenticatedHomologacaoRouteImport } from './routes/_authenticated/homologacao'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedGuiasRouteImport } from './routes/_authenticated/guias'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCompetenciasRouteImport } from './routes/_authenticated/competencias'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicTestSwitchingRouteImport } from './routes/api/public/test-switching'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedPortalProcessosIdRouteImport } from './routes/_authenticated/portal-processos.$id'
import { Route as AuthenticatedIntegracoesOmieRouteImport } from './routes/_authenticated/integracoes.omie'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicHooksCompetenceMonthlyGenerationRouteImport } from './routes/api/public/hooks/competence-monthly-generation'
import { Route as ApiPublicHooksCleanupChatOrphansRouteImport } from './routes/api/public/hooks/cleanup-chat-orphans'
import { Route as AuthenticatedMeuMesClientIdCompetenceRouteImport } from './routes/_authenticated/meu-mes_.$clientId.$competence'
import { Route as AuthenticatedCompetenciasClientIdCompetenceRouteImport } from './routes/_authenticated/competencias_.$clientId.$competence'

const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidadesRoute = AuthenticatedValidadesRouteImport.update({
  id: '/validades',
  path: '/validades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosModelosRoute =
  AuthenticatedProcessosModelosRouteImport.update({
    id: '/processos-modelos',
    path: '/processos-modelos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalProcessosRoute =
  AuthenticatedPortalProcessosRouteImport.update({
    id: '/portal-processos',
    path: '/portal-processos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasPendenciasRoute =
  AuthenticatedMinhasPendenciasRouteImport.update({
    id: '/minhas-pendencias',
    path: '/minhas-pendencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaAreaRoute = AuthenticatedMinhaAreaRouteImport.update({
  id: '/minha-area',
  path: '/minha-area',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusProcessosRoute =
  AuthenticatedMeusProcessosRouteImport.update({
    id: '/meus-processos',
    path: '/meus-processos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusDocumentosRoute =
  AuthenticatedMeusDocumentosRouteImport.update({
    id: '/meus-documentos',
    path: '/meus-documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuMesRoute = AuthenticatedMeuMesRouteImport.update({
  id: '/meu-mes',
  path: '/meu-mes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteracoesRoute = AuthenticatedInteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomologacaoRoute =
  AuthenticatedHomologacaoRouteImport.update({
    id: '/homologacao',
    path: '/homologacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuiasRoute = AuthenticatedGuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetenciasRoute =
  AuthenticatedCompetenciasRouteImport.update({
    id: '/competencias',
    path: '/competencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTestSwitchingRoute = ApiPublicTestSwitchingRouteImport.update({
  id: '/api/public/test-switching',
  path: '/api/public/test-switching',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedPortalProcessosIdRoute =
  AuthenticatedPortalProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalProcessosRoute,
  } as any)
const AuthenticatedIntegracoesOmieRoute =
  AuthenticatedIntegracoesOmieRouteImport.update({
    id: '/integracoes/omie',
    path: '/integracoes/omie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCompetenceMonthlyGenerationRoute =
  ApiPublicHooksCompetenceMonthlyGenerationRouteImport.update({
    id: '/api/public/hooks/competence-monthly-generation',
    path: '/api/public/hooks/competence-monthly-generation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCleanupChatOrphansRoute =
  ApiPublicHooksCleanupChatOrphansRouteImport.update({
    id: '/api/public/hooks/cleanup-chat-orphans',
    path: '/api/public/hooks/cleanup-chat-orphans',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMeuMesClientIdCompetenceRoute =
  AuthenticatedMeuMesClientIdCompetenceRouteImport.update({
    id: '/meu-mes_/$clientId/$competence',
    path: '/meu-mes/$clientId/$competence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetenciasClientIdCompetenceRoute =
  AuthenticatedCompetenciasClientIdCompetenceRouteImport.update({
    id: '/competencias_/$clientId/$competence',
    path: '/competencias/$clientId/$competence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/seguranca': typeof SegurancaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/competencias': typeof AuthenticatedCompetenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/guias': typeof AuthenticatedGuiasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/homologacao': typeof AuthenticatedHomologacaoRoute
  '/interacoes': typeof AuthenticatedInteracoesRoute
  '/meu-mes': typeof AuthenticatedMeuMesRoute
  '/meus-documentos': typeof AuthenticatedMeusDocumentosRoute
  '/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/minha-area': typeof AuthenticatedMinhaAreaRoute
  '/minhas-pendencias': typeof AuthenticatedMinhasPendenciasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/portal-processos': typeof AuthenticatedPortalProcessosRouteWithChildren
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/processos-modelos': typeof AuthenticatedProcessosModelosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/validades': typeof AuthenticatedValidadesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/integracoes/omie': typeof AuthenticatedIntegracoesOmieRoute
  '/portal-processos/$id': typeof AuthenticatedPortalProcessosIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/api/public/test-switching': typeof ApiPublicTestSwitchingRoute
  '/competencias/$clientId/$competence': typeof AuthenticatedCompetenciasClientIdCompetenceRoute
  '/meu-mes/$clientId/$competence': typeof AuthenticatedMeuMesClientIdCompetenceRoute
  '/api/public/hooks/cleanup-chat-orphans': typeof ApiPublicHooksCleanupChatOrphansRoute
  '/api/public/hooks/competence-monthly-generation': typeof ApiPublicHooksCompetenceMonthlyGenerationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/seguranca': typeof SegurancaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/competencias': typeof AuthenticatedCompetenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/guias': typeof AuthenticatedGuiasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/homologacao': typeof AuthenticatedHomologacaoRoute
  '/interacoes': typeof AuthenticatedInteracoesRoute
  '/meu-mes': typeof AuthenticatedMeuMesRoute
  '/meus-documentos': typeof AuthenticatedMeusDocumentosRoute
  '/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/minha-area': typeof AuthenticatedMinhaAreaRoute
  '/minhas-pendencias': typeof AuthenticatedMinhasPendenciasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/portal-processos': typeof AuthenticatedPortalProcessosRouteWithChildren
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/processos-modelos': typeof AuthenticatedProcessosModelosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/validades': typeof AuthenticatedValidadesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/integracoes/omie': typeof AuthenticatedIntegracoesOmieRoute
  '/portal-processos/$id': typeof AuthenticatedPortalProcessosIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/api/public/test-switching': typeof ApiPublicTestSwitchingRoute
  '/competencias/$clientId/$competence': typeof AuthenticatedCompetenciasClientIdCompetenceRoute
  '/meu-mes/$clientId/$competence': typeof AuthenticatedMeuMesClientIdCompetenceRoute
  '/api/public/hooks/cleanup-chat-orphans': typeof ApiPublicHooksCleanupChatOrphansRoute
  '/api/public/hooks/competence-monthly-generation': typeof ApiPublicHooksCompetenceMonthlyGenerationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/seguranca': typeof SegurancaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/competencias': typeof AuthenticatedCompetenciasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/guias': typeof AuthenticatedGuiasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/homologacao': typeof AuthenticatedHomologacaoRoute
  '/_authenticated/interacoes': typeof AuthenticatedInteracoesRoute
  '/_authenticated/meu-mes': typeof AuthenticatedMeuMesRoute
  '/_authenticated/meus-documentos': typeof AuthenticatedMeusDocumentosRoute
  '/_authenticated/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/_authenticated/minha-area': typeof AuthenticatedMinhaAreaRoute
  '/_authenticated/minhas-pendencias': typeof AuthenticatedMinhasPendenciasRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/portal-processos': typeof AuthenticatedPortalProcessosRouteWithChildren
  '/_authenticated/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/_authenticated/processos-modelos': typeof AuthenticatedProcessosModelosRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/validades': typeof AuthenticatedValidadesRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/integracoes/omie': typeof AuthenticatedIntegracoesOmieRoute
  '/_authenticated/portal-processos/$id': typeof AuthenticatedPortalProcessosIdRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
  '/api/public/test-switching': typeof ApiPublicTestSwitchingRoute
  '/_authenticated/competencias_/$clientId/$competence': typeof AuthenticatedCompetenciasClientIdCompetenceRoute
  '/_authenticated/meu-mes_/$clientId/$competence': typeof AuthenticatedMeuMesClientIdCompetenceRoute
  '/api/public/hooks/cleanup-chat-orphans': typeof ApiPublicHooksCleanupChatOrphansRoute
  '/api/public/hooks/competence-monthly-generation': typeof ApiPublicHooksCompetenceMonthlyGenerationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/seguranca'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checklist'
    | '/clientes'
    | '/colaboradores'
    | '/competencias'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/guias'
    | '/historico'
    | '/homologacao'
    | '/interacoes'
    | '/meu-mes'
    | '/meus-documentos'
    | '/meus-processos'
    | '/minha-area'
    | '/minhas-pendencias'
    | '/modelos'
    | '/notificacoes'
    | '/pendencias'
    | '/planos'
    | '/portal-processos'
    | '/processos'
    | '/processos-modelos'
    | '/solicitacoes'
    | '/validades'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/clientes/$id'
    | '/integracoes/omie'
    | '/portal-processos/$id'
    | '/processos/$id'
    | '/api/public/test-switching'
    | '/competencias/$clientId/$competence'
    | '/meu-mes/$clientId/$competence'
    | '/api/public/hooks/cleanup-chat-orphans'
    | '/api/public/hooks/competence-monthly-generation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/seguranca'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/checklist'
    | '/clientes'
    | '/colaboradores'
    | '/competencias'
    | '/configuracoes'
    | '/dashboard'
    | '/documentos'
    | '/guias'
    | '/historico'
    | '/homologacao'
    | '/interacoes'
    | '/meu-mes'
    | '/meus-documentos'
    | '/meus-processos'
    | '/minha-area'
    | '/minhas-pendencias'
    | '/modelos'
    | '/notificacoes'
    | '/pendencias'
    | '/planos'
    | '/portal-processos'
    | '/processos'
    | '/processos-modelos'
    | '/solicitacoes'
    | '/validades'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/clientes/$id'
    | '/integracoes/omie'
    | '/portal-processos/$id'
    | '/processos/$id'
    | '/api/public/test-switching'
    | '/competencias/$clientId/$competence'
    | '/meu-mes/$clientId/$competence'
    | '/api/public/hooks/cleanup-chat-orphans'
    | '/api/public/hooks/competence-monthly-generation'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/seguranca'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/checklist'
    | '/_authenticated/clientes'
    | '/_authenticated/colaboradores'
    | '/_authenticated/competencias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/guias'
    | '/_authenticated/historico'
    | '/_authenticated/homologacao'
    | '/_authenticated/interacoes'
    | '/_authenticated/meu-mes'
    | '/_authenticated/meus-documentos'
    | '/_authenticated/meus-processos'
    | '/_authenticated/minha-area'
    | '/_authenticated/minhas-pendencias'
    | '/_authenticated/modelos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pendencias'
    | '/_authenticated/planos'
    | '/_authenticated/portal-processos'
    | '/_authenticated/processos'
    | '/_authenticated/processos-modelos'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/validades'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/integracoes/omie'
    | '/_authenticated/portal-processos/$id'
    | '/_authenticated/processos/$id'
    | '/api/public/test-switching'
    | '/_authenticated/competencias_/$clientId/$competence'
    | '/_authenticated/meu-mes_/$clientId/$competence'
    | '/api/public/hooks/cleanup-chat-orphans'
    | '/api/public/hooks/competence-monthly-generation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SegurancaRoute: typeof SegurancaRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicTestSwitchingRoute: typeof ApiPublicTestSwitchingRoute
  ApiPublicHooksCleanupChatOrphansRoute: typeof ApiPublicHooksCleanupChatOrphansRoute
  ApiPublicHooksCompetenceMonthlyGenerationRoute: typeof ApiPublicHooksCompetenceMonthlyGenerationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validades': {
      id: '/_authenticated/validades'
      path: '/validades'
      fullPath: '/validades'
      preLoaderRoute: typeof AuthenticatedValidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos-modelos': {
      id: '/_authenticated/processos-modelos'
      path: '/processos-modelos'
      fullPath: '/processos-modelos'
      preLoaderRoute: typeof AuthenticatedProcessosModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-processos': {
      id: '/_authenticated/portal-processos'
      path: '/portal-processos'
      fullPath: '/portal-processos'
      preLoaderRoute: typeof AuthenticatedPortalProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-pendencias': {
      id: '/_authenticated/minhas-pendencias'
      path: '/minhas-pendencias'
      fullPath: '/minhas-pendencias'
      preLoaderRoute: typeof AuthenticatedMinhasPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-area': {
      id: '/_authenticated/minha-area'
      path: '/minha-area'
      fullPath: '/minha-area'
      preLoaderRoute: typeof AuthenticatedMinhaAreaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-processos': {
      id: '/_authenticated/meus-processos'
      path: '/meus-processos'
      fullPath: '/meus-processos'
      preLoaderRoute: typeof AuthenticatedMeusProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-documentos': {
      id: '/_authenticated/meus-documentos'
      path: '/meus-documentos'
      fullPath: '/meus-documentos'
      preLoaderRoute: typeof AuthenticatedMeusDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-mes': {
      id: '/_authenticated/meu-mes'
      path: '/meu-mes'
      fullPath: '/meu-mes'
      preLoaderRoute: typeof AuthenticatedMeuMesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interacoes': {
      id: '/_authenticated/interacoes'
      path: '/interacoes'
      fullPath: '/interacoes'
      preLoaderRoute: typeof AuthenticatedInteracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/homologacao': {
      id: '/_authenticated/homologacao'
      path: '/homologacao'
      fullPath: '/homologacao'
      preLoaderRoute: typeof AuthenticatedHomologacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guias': {
      id: '/_authenticated/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof AuthenticatedGuiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competencias': {
      id: '/_authenticated/competencias'
      path: '/competencias'
      fullPath: '/competencias'
      preLoaderRoute: typeof AuthenticatedCompetenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-switching': {
      id: '/api/public/test-switching'
      path: '/api/public/test-switching'
      fullPath: '/api/public/test-switching'
      preLoaderRoute: typeof ApiPublicTestSwitchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/portal-processos/$id': {
      id: '/_authenticated/portal-processos/$id'
      path: '/$id'
      fullPath: '/portal-processos/$id'
      preLoaderRoute: typeof AuthenticatedPortalProcessosIdRouteImport
      parentRoute: typeof AuthenticatedPortalProcessosRoute
    }
    '/_authenticated/integracoes/omie': {
      id: '/_authenticated/integracoes/omie'
      path: '/integracoes/omie'
      fullPath: '/integracoes/omie'
      preLoaderRoute: typeof AuthenticatedIntegracoesOmieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/competence-monthly-generation': {
      id: '/api/public/hooks/competence-monthly-generation'
      path: '/api/public/hooks/competence-monthly-generation'
      fullPath: '/api/public/hooks/competence-monthly-generation'
      preLoaderRoute: typeof ApiPublicHooksCompetenceMonthlyGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-chat-orphans': {
      id: '/api/public/hooks/cleanup-chat-orphans'
      path: '/api/public/hooks/cleanup-chat-orphans'
      fullPath: '/api/public/hooks/cleanup-chat-orphans'
      preLoaderRoute: typeof ApiPublicHooksCleanupChatOrphansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/meu-mes_/$clientId/$competence': {
      id: '/_authenticated/meu-mes_/$clientId/$competence'
      path: '/meu-mes/$clientId/$competence'
      fullPath: '/meu-mes/$clientId/$competence'
      preLoaderRoute: typeof AuthenticatedMeuMesClientIdCompetenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competencias_/$clientId/$competence': {
      id: '/_authenticated/competencias_/$clientId/$competence'
      path: '/competencias/$clientId/$competence'
      fullPath: '/competencias/$clientId/$competence'
      preLoaderRoute: typeof AuthenticatedCompetenciasClientIdCompetenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedPortalProcessosRouteChildren {
  AuthenticatedPortalProcessosIdRoute: typeof AuthenticatedPortalProcessosIdRoute
}

const AuthenticatedPortalProcessosRouteChildren: AuthenticatedPortalProcessosRouteChildren =
  {
    AuthenticatedPortalProcessosIdRoute: AuthenticatedPortalProcessosIdRoute,
  }

const AuthenticatedPortalProcessosRouteWithChildren =
  AuthenticatedPortalProcessosRoute._addFileChildren(
    AuthenticatedPortalProcessosRouteChildren,
  )

interface AuthenticatedProcessosRouteChildren {
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
}

const AuthenticatedProcessosRouteChildren: AuthenticatedProcessosRouteChildren =
  {
    AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  }

const AuthenticatedProcessosRouteWithChildren =
  AuthenticatedProcessosRoute._addFileChildren(
    AuthenticatedProcessosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedCompetenciasRoute: typeof AuthenticatedCompetenciasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedGuiasRoute: typeof AuthenticatedGuiasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedHomologacaoRoute: typeof AuthenticatedHomologacaoRoute
  AuthenticatedInteracoesRoute: typeof AuthenticatedInteracoesRoute
  AuthenticatedMeuMesRoute: typeof AuthenticatedMeuMesRoute
  AuthenticatedMeusDocumentosRoute: typeof AuthenticatedMeusDocumentosRoute
  AuthenticatedMeusProcessosRoute: typeof AuthenticatedMeusProcessosRoute
  AuthenticatedMinhaAreaRoute: typeof AuthenticatedMinhaAreaRoute
  AuthenticatedMinhasPendenciasRoute: typeof AuthenticatedMinhasPendenciasRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPortalProcessosRoute: typeof AuthenticatedPortalProcessosRouteWithChildren
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRouteWithChildren
  AuthenticatedProcessosModelosRoute: typeof AuthenticatedProcessosModelosRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedValidadesRoute: typeof AuthenticatedValidadesRoute
  AuthenticatedIntegracoesOmieRoute: typeof AuthenticatedIntegracoesOmieRoute
  AuthenticatedCompetenciasClientIdCompetenceRoute: typeof AuthenticatedCompetenciasClientIdCompetenceRoute
  AuthenticatedMeuMesClientIdCompetenceRoute: typeof AuthenticatedMeuMesClientIdCompetenceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedCompetenciasRoute: AuthenticatedCompetenciasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedGuiasRoute: AuthenticatedGuiasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedHomologacaoRoute: AuthenticatedHomologacaoRoute,
  AuthenticatedInteracoesRoute: AuthenticatedInteracoesRoute,
  AuthenticatedMeuMesRoute: AuthenticatedMeuMesRoute,
  AuthenticatedMeusDocumentosRoute: AuthenticatedMeusDocumentosRoute,
  AuthenticatedMeusProcessosRoute: AuthenticatedMeusProcessosRoute,
  AuthenticatedMinhaAreaRoute: AuthenticatedMinhaAreaRoute,
  AuthenticatedMinhasPendenciasRoute: AuthenticatedMinhasPendenciasRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPortalProcessosRoute:
    AuthenticatedPortalProcessosRouteWithChildren,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRouteWithChildren,
  AuthenticatedProcessosModelosRoute: AuthenticatedProcessosModelosRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedValidadesRoute: AuthenticatedValidadesRoute,
  AuthenticatedIntegracoesOmieRoute: AuthenticatedIntegracoesOmieRoute,
  AuthenticatedCompetenciasClientIdCompetenceRoute:
    AuthenticatedCompetenciasClientIdCompetenceRoute,
  AuthenticatedMeuMesClientIdCompetenceRoute:
    AuthenticatedMeuMesClientIdCompetenceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SegurancaRoute: SegurancaRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicTestSwitchingRoute: ApiPublicTestSwitchingRoute,
  ApiPublicHooksCleanupChatOrphansRoute: ApiPublicHooksCleanupChatOrphansRoute,
  ApiPublicHooksCompetenceMonthlyGenerationRoute:
    ApiPublicHooksCompetenceMonthlyGenerationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
