/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedValidadesRouteImport } from './routes/_authenticated/validades'
import { Route as AuthenticatedSolicitacoesRouteImport } from './routes/_authenticated/solicitacoes'
import { Route as AuthenticatedProcessosModelosRouteImport } from './routes/_authenticated/processos-modelos'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated/processos'
import { Route as AuthenticatedPortalProcessosRouteImport } from './routes/_authenticated/portal-processos'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedModelosRouteImport } from './routes/_authenticated/modelos'
import { Route as AuthenticatedMinhasPendenciasRouteImport } from './routes/_authenticated/minhas-pendencias'
import { Route as AuthenticatedMinhaAreaRouteImport } from './routes/_authenticated/minha-area'
import { Route as AuthenticatedMeusProcessosRouteImport } from './routes/_authenticated/meus-processos'
import { Route as AuthenticatedMeusDocumentosRouteImport } from './routes/_authenticated/meus-documentos'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedInteracoesRouteImport } from './routes/_authenticated/interacoes'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedGuiasRouteImport } from './routes/_authenticated/guias'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedProcessosIdRouteImport } from './routes/_authenticated/processos.$id'
import { Route as AuthenticatedPortalProcessosIdRouteImport } from './routes/_authenticated/portal-processos.$id'
import { Route as AuthenticatedIntegracoesOmieRouteImport } from './routes/_authenticated/integracoes.omie'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'

const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValidadesRoute = AuthenticatedValidadesRouteImport.update({
  id: '/validades',
  path: '/validades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSolicitacoesRoute =
  AuthenticatedSolicitacoesRouteImport.update({
    id: '/solicitacoes',
    path: '/solicitacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosModelosRoute =
  AuthenticatedProcessosModelosRouteImport.update({
    id: '/processos-modelos',
    path: '/processos-modelos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalProcessosRoute =
  AuthenticatedPortalProcessosRouteImport.update({
    id: '/portal-processos',
    path: '/portal-processos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelosRoute = AuthenticatedModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasPendenciasRoute =
  AuthenticatedMinhasPendenciasRouteImport.update({
    id: '/minhas-pendencias',
    path: '/minhas-pendencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaAreaRoute = AuthenticatedMinhaAreaRouteImport.update({
  id: '/minha-area',
  path: '/minha-area',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusProcessosRoute =
  AuthenticatedMeusProcessosRouteImport.update({
    id: '/meus-processos',
    path: '/meus-processos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeusDocumentosRoute =
  AuthenticatedMeusDocumentosRouteImport.update({
    id: '/meus-documentos',
    path: '/meus-documentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInteracoesRoute = AuthenticatedInteracoesRouteImport.update({
  id: '/interacoes',
  path: '/interacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuiasRoute = AuthenticatedGuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcessosIdRoute =
  AuthenticatedProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedPortalProcessosIdRoute =
  AuthenticatedPortalProcessosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPortalProcessosRoute,
  } as any)
const AuthenticatedIntegracoesOmieRoute =
  AuthenticatedIntegracoesOmieRouteImport.update({
    id: '/integracoes/omie',
    path: '/integracoes/omie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/seguranca': typeof SegurancaRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/guias': typeof AuthenticatedGuiasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/interacoes': typeof AuthenticatedInteracoesRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/meus-documentos': typeof AuthenticatedMeusDocumentosRoute
  '/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/minha-area': typeof AuthenticatedMinhaAreaRoute
  '/minhas-pendencias': typeof AuthenticatedMinhasPendenciasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/portal-processos': typeof AuthenticatedPortalProcessosRouteWithChildren
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/processos-modelos': typeof AuthenticatedProcessosModelosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/validades': typeof AuthenticatedValidadesRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/integracoes/omie': typeof AuthenticatedIntegracoesOmieRoute
  '/portal-processos/$id': typeof AuthenticatedPortalProcessosIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/seguranca': typeof SegurancaRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/guias': typeof AuthenticatedGuiasRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/interacoes': typeof AuthenticatedInteracoesRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/meus-documentos': typeof AuthenticatedMeusDocumentosRoute
  '/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/minha-area': typeof AuthenticatedMinhaAreaRoute
  '/minhas-pendencias': typeof AuthenticatedMinhasPendenciasRoute
  '/modelos': typeof AuthenticatedModelosRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/portal-processos': typeof AuthenticatedPortalProcessosRouteWithChildren
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/processos-modelos': typeof AuthenticatedProcessosModelosRoute
  '/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/validades': typeof AuthenticatedValidadesRoute
  '/': typeof AuthenticatedIndexRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/integracoes/omie': typeof AuthenticatedIntegracoesOmieRoute
  '/portal-processos/$id': typeof AuthenticatedPortalProcessosIdRoute
  '/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/seguranca': typeof SegurancaRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/guias': typeof AuthenticatedGuiasRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/interacoes': typeof AuthenticatedInteracoesRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/meus-documentos': typeof AuthenticatedMeusDocumentosRoute
  '/_authenticated/meus-processos': typeof AuthenticatedMeusProcessosRoute
  '/_authenticated/minha-area': typeof AuthenticatedMinhaAreaRoute
  '/_authenticated/minhas-pendencias': typeof AuthenticatedMinhasPendenciasRoute
  '/_authenticated/modelos': typeof AuthenticatedModelosRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/portal-processos': typeof AuthenticatedPortalProcessosRouteWithChildren
  '/_authenticated/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/_authenticated/processos-modelos': typeof AuthenticatedProcessosModelosRoute
  '/_authenticated/solicitacoes': typeof AuthenticatedSolicitacoesRoute
  '/_authenticated/validades': typeof AuthenticatedValidadesRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/integracoes/omie': typeof AuthenticatedIntegracoesOmieRoute
  '/_authenticated/portal-processos/$id': typeof AuthenticatedPortalProcessosIdRoute
  '/_authenticated/processos/$id': typeof AuthenticatedProcessosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/seguranca'
    | '/checklist'
    | '/clientes'
    | '/colaboradores'
    | '/configuracoes'
    | '/documentos'
    | '/guias'
    | '/historico'
    | '/interacoes'
    | '/kanban'
    | '/meus-documentos'
    | '/meus-processos'
    | '/minha-area'
    | '/minhas-pendencias'
    | '/modelos'
    | '/notificacoes'
    | '/pendencias'
    | '/planos'
    | '/portal-processos'
    | '/processos'
    | '/processos-modelos'
    | '/solicitacoes'
    | '/validades'
    | '/clientes/$id'
    | '/integracoes/omie'
    | '/portal-processos/$id'
    | '/processos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/seguranca'
    | '/checklist'
    | '/clientes'
    | '/colaboradores'
    | '/configuracoes'
    | '/documentos'
    | '/guias'
    | '/historico'
    | '/interacoes'
    | '/kanban'
    | '/meus-documentos'
    | '/meus-processos'
    | '/minha-area'
    | '/minhas-pendencias'
    | '/modelos'
    | '/notificacoes'
    | '/pendencias'
    | '/planos'
    | '/portal-processos'
    | '/processos'
    | '/processos-modelos'
    | '/solicitacoes'
    | '/validades'
    | '/'
    | '/clientes/$id'
    | '/integracoes/omie'
    | '/portal-processos/$id'
    | '/processos/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/seguranca'
    | '/_authenticated/checklist'
    | '/_authenticated/clientes'
    | '/_authenticated/colaboradores'
    | '/_authenticated/configuracoes'
    | '/_authenticated/documentos'
    | '/_authenticated/guias'
    | '/_authenticated/historico'
    | '/_authenticated/interacoes'
    | '/_authenticated/kanban'
    | '/_authenticated/meus-documentos'
    | '/_authenticated/meus-processos'
    | '/_authenticated/minha-area'
    | '/_authenticated/minhas-pendencias'
    | '/_authenticated/modelos'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pendencias'
    | '/_authenticated/planos'
    | '/_authenticated/portal-processos'
    | '/_authenticated/processos'
    | '/_authenticated/processos-modelos'
    | '/_authenticated/solicitacoes'
    | '/_authenticated/validades'
    | '/_authenticated/'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/integracoes/omie'
    | '/_authenticated/portal-processos/$id'
    | '/_authenticated/processos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SegurancaRoute: typeof SegurancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/validades': {
      id: '/_authenticated/validades'
      path: '/validades'
      fullPath: '/validades'
      preLoaderRoute: typeof AuthenticatedValidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitacoes': {
      id: '/_authenticated/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/solicitacoes'
      preLoaderRoute: typeof AuthenticatedSolicitacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos-modelos': {
      id: '/_authenticated/processos-modelos'
      path: '/processos-modelos'
      fullPath: '/processos-modelos'
      preLoaderRoute: typeof AuthenticatedProcessosModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal-processos': {
      id: '/_authenticated/portal-processos'
      path: '/portal-processos'
      fullPath: '/portal-processos'
      preLoaderRoute: typeof AuthenticatedPortalProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modelos': {
      id: '/_authenticated/modelos'
      path: '/modelos'
      fullPath: '/modelos'
      preLoaderRoute: typeof AuthenticatedModelosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-pendencias': {
      id: '/_authenticated/minhas-pendencias'
      path: '/minhas-pendencias'
      fullPath: '/minhas-pendencias'
      preLoaderRoute: typeof AuthenticatedMinhasPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-area': {
      id: '/_authenticated/minha-area'
      path: '/minha-area'
      fullPath: '/minha-area'
      preLoaderRoute: typeof AuthenticatedMinhaAreaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-processos': {
      id: '/_authenticated/meus-processos'
      path: '/meus-processos'
      fullPath: '/meus-processos'
      preLoaderRoute: typeof AuthenticatedMeusProcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-documentos': {
      id: '/_authenticated/meus-documentos'
      path: '/meus-documentos'
      fullPath: '/meus-documentos'
      preLoaderRoute: typeof AuthenticatedMeusDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interacoes': {
      id: '/_authenticated/interacoes'
      path: '/interacoes'
      fullPath: '/interacoes'
      preLoaderRoute: typeof AuthenticatedInteracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guias': {
      id: '/_authenticated/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof AuthenticatedGuiasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/processos/$id': {
      id: '/_authenticated/processos/$id'
      path: '/$id'
      fullPath: '/processos/$id'
      preLoaderRoute: typeof AuthenticatedProcessosIdRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/portal-processos/$id': {
      id: '/_authenticated/portal-processos/$id'
      path: '/$id'
      fullPath: '/portal-processos/$id'
      preLoaderRoute: typeof AuthenticatedPortalProcessosIdRouteImport
      parentRoute: typeof AuthenticatedPortalProcessosRoute
    }
    '/_authenticated/integracoes/omie': {
      id: '/_authenticated/integracoes/omie'
      path: '/integracoes/omie'
      fullPath: '/integracoes/omie'
      preLoaderRoute: typeof AuthenticatedIntegracoesOmieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedPortalProcessosRouteChildren {
  AuthenticatedPortalProcessosIdRoute: typeof AuthenticatedPortalProcessosIdRoute
}

const AuthenticatedPortalProcessosRouteChildren: AuthenticatedPortalProcessosRouteChildren =
  {
    AuthenticatedPortalProcessosIdRoute: AuthenticatedPortalProcessosIdRoute,
  }

const AuthenticatedPortalProcessosRouteWithChildren =
  AuthenticatedPortalProcessosRoute._addFileChildren(
    AuthenticatedPortalProcessosRouteChildren,
  )

interface AuthenticatedProcessosRouteChildren {
  AuthenticatedProcessosIdRoute: typeof AuthenticatedProcessosIdRoute
}

const AuthenticatedProcessosRouteChildren: AuthenticatedProcessosRouteChildren =
  {
    AuthenticatedProcessosIdRoute: AuthenticatedProcessosIdRoute,
  }

const AuthenticatedProcessosRouteWithChildren =
  AuthenticatedProcessosRoute._addFileChildren(
    AuthenticatedProcessosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedGuiasRoute: typeof AuthenticatedGuiasRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedInteracoesRoute: typeof AuthenticatedInteracoesRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedMeusDocumentosRoute: typeof AuthenticatedMeusDocumentosRoute
  AuthenticatedMeusProcessosRoute: typeof AuthenticatedMeusProcessosRoute
  AuthenticatedMinhaAreaRoute: typeof AuthenticatedMinhaAreaRoute
  AuthenticatedMinhasPendenciasRoute: typeof AuthenticatedMinhasPendenciasRoute
  AuthenticatedModelosRoute: typeof AuthenticatedModelosRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedPortalProcessosRoute: typeof AuthenticatedPortalProcessosRouteWithChildren
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRouteWithChildren
  AuthenticatedProcessosModelosRoute: typeof AuthenticatedProcessosModelosRoute
  AuthenticatedSolicitacoesRoute: typeof AuthenticatedSolicitacoesRoute
  AuthenticatedValidadesRoute: typeof AuthenticatedValidadesRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedIntegracoesOmieRoute: typeof AuthenticatedIntegracoesOmieRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedGuiasRoute: AuthenticatedGuiasRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedInteracoesRoute: AuthenticatedInteracoesRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedMeusDocumentosRoute: AuthenticatedMeusDocumentosRoute,
  AuthenticatedMeusProcessosRoute: AuthenticatedMeusProcessosRoute,
  AuthenticatedMinhaAreaRoute: AuthenticatedMinhaAreaRoute,
  AuthenticatedMinhasPendenciasRoute: AuthenticatedMinhasPendenciasRoute,
  AuthenticatedModelosRoute: AuthenticatedModelosRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedPortalProcessosRoute:
    AuthenticatedPortalProcessosRouteWithChildren,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRouteWithChildren,
  AuthenticatedProcessosModelosRoute: AuthenticatedProcessosModelosRoute,
  AuthenticatedSolicitacoesRoute: AuthenticatedSolicitacoesRoute,
  AuthenticatedValidadesRoute: AuthenticatedValidadesRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedIntegracoesOmieRoute: AuthenticatedIntegracoesOmieRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SegurancaRoute: SegurancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
